### ISSUE TITLE
Optional lazyInject

### ISSUE THREAD

**Issue by CrazyFlasher** [inversify/inversify-inject-decorators#160]
Possible?
Currently this code throws run-time error if I add optional:
```ts
@lazyInjectNamed("string", "commandMapperId") @optional()
    private commandMapperId!: string;
```
```
Error: Missing required @injectable annotation in: for property commandMapperId in class ExecuteCliCommand.
    at _getServiceIdentifierForProperty (node_modules\inversify\src\planning\reflection_utils.ts:145:11)
    at getClassPropsAsTargets (node_modules\inversify\src\planning\reflection_utils.ts:173:31)
    at getTargets (node_modules\inversify\src\planning\reflection_utils.ts:54:27)
    at getDependencies (node_modules\inversify\src\planning\reflection_utils.ts:14:10)
    at C:\work\projects\domwires-devkit-ts\node_modules\inversify\src\planning\planner.ts:179:43
    at Array.forEach (<anonymous>)
```

**Comment by CrazyFlasher** [comment]
No reason to use lazyInject here :)
